data_path: /home/mcreamer/Documents/data_sets/fun_con/
# some data sets are unreliable, remove them
bad_data_sets: []

# the calcium dynamics always look strange at the start of a recording, possibly due to the laser being turned on
# cut out the first ~15 seconds to let the system equilibrate
start_index: 25

num_data_sets: 10
force_preprocess: False
interpolate_nans: True

param_props:
  update:
    dynamics_weights: True
    dynamics_input_weights: True
    dynamics_offset: False
    dynamics_cov: True
    emissions_weights: False
    emissions_input_weights: False
    emissions_offset: False
    emissions_cov: True

  shape:
    dynamics_input_weights: diag
    dynamics_cov: full
    emissions_cov: full

  mask:
    dynamics_input_weights: Null

device: cpu
dtype: float64

# gradient descent parameters
# choices are: gradient_descent and batch_sgd
dynamics_lags: 1
dynamics_input_lags: 1
fit_type: em
num_train_steps: 50
verbose: True

plot_figures: True
model_save_folder: trained_models



