device: cpu
dtype: float64

# data parameters
dynamics_dim: 80
emissions_dim: 80
input_dim: 80
num_time: 5000
num_data_sets: 56
scattered_nan_freq: 0.0
lost_emission_freq: 0.5
num_lags: 4
input_time_scale: 50

# initialize a linear gaussian ssm model
param_props:
  update:
    dynamics_weights: True
    dynamics_input_weights: True
    dynamics_offset: False
    dynamics_cov: True
    emissions_weights: False
    emissions_input_weights: False
    emissions_offset: False
    emissions_cov: True

  shape:
    dynamics_input_weights: diag
    dynamics_cov: full
    emissions_cov: full

  mask:
    dynamics_input_weights: Null

# training parameters
num_train_steps: 40
verbose: True
random_seed: 0

plot_figures: True
model_save_folder: trained_models
synth_data_save_folder: example_data