device: cpu
dtype: float64

# data parameters
dynamics_dim: 5
emissions_dim: 5
input_dim: 5
num_time: 1000
num_data_sets: 1
scattered_nan_freq: 0.0
lost_emission_freq: 0.0
dynamics_lags: 1
dynamics_input_lags: 1
input_time_scale: 0

# initialize a linear gaussian ssm model
param_props:
  update:
    dynamics_weights: True
    dynamics_input_weights: True
    dynamics_offset: False
    dynamics_cov: True
    emissions_weights: False
    emissions_input_weights: False
    emissions_offset: False
    emissions_cov: True

  shape:
    dynamics_input_weights: diag
    dynamics_cov: full
    emissions_cov: full

  mask:
    dynamics_input_weights: Null

# training parameters
num_train_steps: 20
verbose: True
random_seed: 0

plot_figures: True
model_save_folder: trained_models
synth_data_save_folder: example_data