device: cpu
dtype: float64

# model parameters
dynamics_dim: 5
emissions_dim: 5
input_dim: 5
num_time: 1000
num_data_sets: 10
nan_freq: 0.0

# gradient descent parameters
# choices are: gradient_descent and batch_sgd
fit_type: em
num_grad_steps: 10
learning_rate: 0.1
verbose: True
random_seed: 0

plot_figures: True
model_save_folder: trained_models
synth_data_save_folder: example_data